export type FormatCategory =
  | "image"
  | "document"
  | "audio"
  | "video"
  | "spreadsheet"
  | "data"
  | "archive";

export interface FormatDefinition {
  label: string;
  category: FormatCategory;
  mimeTypes: string[];
  extensions: string[];
  safe: boolean; // safe to display in browser?
  compatibleOutputs: string[];
}

export const FORMATS: Record<string, FormatDefinition> = {
  // Images
  jpg: {
    label: "JPEG Image",
    category: "image",
    mimeTypes: ["image/jpeg"],
    extensions: ["jpg", "jpeg"],
    safe: true,
    compatibleOutputs: [
      "png",
      "webp",
      "gif",
      "bmp",
      "tiff",
      "avif",
      "ico",
      "pdf",
    ],
  },
  jpeg: {
    label: "JPEG Image",
    category: "image",
    mimeTypes: ["image/jpeg"],
    extensions: ["jpg", "jpeg"],
    safe: true,
    compatibleOutputs: [
      "png",
      "webp",
      "gif",
      "bmp",
      "tiff",
      "avif",
      "ico",
      "pdf",
    ],
  },
  png: {
    label: "PNG Image",
    category: "image",
    mimeTypes: ["image/png"],
    extensions: ["png"],
    safe: true,
    compatibleOutputs: [
      "jpg",
      "webp",
      "gif",
      "bmp",
      "tiff",
      "avif",
      "ico",
      "pdf",
    ],
  },
  webp: {
    label: "WebP Image",
    category: "image",
    mimeTypes: ["image/webp"],
    extensions: ["webp"],
    safe: true,
    compatibleOutputs: [
      "jpg",
      "png",
      "gif",
      "bmp",
      "tiff",
      "avif",
      "ico",
      "pdf",
    ],
  },
  gif: {
    label: "GIF Image",
    category: "image",
    mimeTypes: ["image/gif"],
    extensions: ["gif"],
    safe: true,
    compatibleOutputs: [
      "jpg",
      "png",
      "webp",
      "bmp",
      "tiff",
      "avif",
      "ico",
      "pdf",
      "mp4",
    ],
  },
  bmp: {
    label: "Bitmap Image",
    category: "image",
    mimeTypes: ["image/bmp"],
    extensions: ["bmp"],
    safe: true,
    compatibleOutputs: [
      "jpg",
      "png",
      "webp",
      "gif",
      "tiff",
      "avif",
      "ico",
      "pdf",
    ],
  },
  tiff: {
    label: "TIFF Image",
    category: "image",
    mimeTypes: ["image/tiff"],
    extensions: ["tiff", "tif"],
    safe: false,
    compatibleOutputs: [
      "jpg",
      "png",
      "webp",
      "gif",
      "bmp",
      "avif",
      "ico",
      "pdf",
    ],
  },
  heic: {
    label: "HEIC Image",
    category: "image",
    mimeTypes: ["image/heic"],
    extensions: ["heic"],
    safe: false,
    compatibleOutputs: [
      "jpg",
      "png",
      "webp",
      "gif",
      "bmp",
      "tiff",
      "avif",
      "ico",
      "pdf",
    ],
  },
  ico: {
    label: "Icon",
    category: "image",
    mimeTypes: ["image/x-icon", "image/vnd.microsoft.icon"],
    extensions: ["ico"],
    safe: true,
    compatibleOutputs: ["png", "jpg", "webp", "gif", "bmp"],
  },
  avif: {
    label: "AVIF Image",
    category: "image",
    mimeTypes: ["image/avif"],
    extensions: ["avif"],
    safe: true,
    compatibleOutputs: [
      "jpg",
      "png",
      "webp",
      "gif",
      "bmp",
      "tiff",
      "ico",
      "pdf",
    ],
  },

  // Documents
  pdf: {
    label: "PDF Document",
    category: "document",
    mimeTypes: ["application/pdf"],
    extensions: ["pdf"],
    safe: false, // Browsers handle it, but not <img>
    compatibleOutputs: ["docx", "txt", "html", "jpg", "png", "webp"],
  },
  docx: {
    label: "Word Document",
    category: "document",
    mimeTypes: [
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    ],
    extensions: ["docx"],
    safe: false,
    compatibleOutputs: ["pdf", "txt", "html", "md"],
  },
  doc: {
    label: "Legacy Word Doc",
    category: "document",
    mimeTypes: ["application/msword"],
    extensions: ["doc"],
    safe: false,
    compatibleOutputs: ["pdf", "docx", "txt", "html"],
  },
  txt: {
    label: "Text File",
    category: "document",
    mimeTypes: ["text/plain"],
    extensions: ["txt"],
    safe: true,
    compatibleOutputs: ["pdf", "docx", "html", "md"],
  },
  rtf: {
    label: "Rich Text",
    category: "document",
    mimeTypes: ["application/rtf"],
    extensions: ["rtf"],
    safe: false,
    compatibleOutputs: ["pdf", "docx", "txt", "html"],
  },
  html: {
    label: "HTML Document",
    category: "document",
    mimeTypes: ["text/html"],
    extensions: ["html", "htm"],
    safe: true,
    compatibleOutputs: ["pdf", "docx", "txt", "md"],
  },
  md: {
    label: "Markdown",
    category: "document",
    mimeTypes: ["text/markdown", "text/x-markdown"],
    extensions: ["md"],
    safe: true,
    compatibleOutputs: ["html", "pdf", "docx", "txt"],
  },

  // Audio
  mp3: {
    label: "MP3 Audio",
    category: "audio",
    mimeTypes: ["audio/mpeg"],
    extensions: ["mp3"],
    safe: true,
    compatibleOutputs: ["wav", "ogg", "aac", "m4a", "flac", "opus", "wma"],
  },
  wav: {
    label: "WAV Audio",
    category: "audio",
    mimeTypes: ["audio/wav", "audio/x-wav"],
    extensions: ["wav"],
    safe: true,
    compatibleOutputs: ["mp3", "ogg", "aac", "m4a", "flac", "opus", "wma"],
  },
  ogg: {
    label: "OGG Audio",
    category: "audio",
    mimeTypes: ["audio/ogg"],
    extensions: ["ogg"],
    safe: true,
    compatibleOutputs: ["mp3", "wav", "aac", "m4a", "flac", "opus", "wma"],
  },
  aac: {
    label: "AAC Audio",
    category: "audio",
    mimeTypes: ["audio/aac"],
    extensions: ["aac"],
    safe: true,
    compatibleOutputs: ["mp3", "wav", "ogg", "m4a", "flac", "opus", "wma"],
  },
  m4a: {
    label: "M4A Audio",
    category: "audio",
    mimeTypes: ["audio/mp4", "audio/x-m4a"],
    extensions: ["m4a"],
    safe: true,
    compatibleOutputs: ["mp3", "wav", "ogg", "aac", "flac", "opus", "wma"],
  },
  flac: {
    label: "FLAC Audio",
    category: "audio",
    mimeTypes: ["audio/flac"],
    extensions: ["flac"],
    safe: false, // Partial browser support
    compatibleOutputs: ["mp3", "wav", "ogg", "aac", "m4a", "opus", "wma"],
  },
  opus: {
    label: "Opus Audio",
    category: "audio",
    mimeTypes: ["audio/opus", "audio/ogg"],
    extensions: ["opus"],
    safe: true,
    compatibleOutputs: ["mp3", "wav", "ogg", "aac", "m4a", "flac", "wma"],
  },
  wma: {
    label: "WMA Audio",
    category: "audio",
    mimeTypes: ["audio/x-ms-wma"],
    extensions: ["wma"],
    safe: false,
    compatibleOutputs: ["mp3", "wav", "ogg", "aac", "m4a", "flac", "opus"],
  },

  // Video
  mp4: {
    label: "MP4 Video",
    category: "video",
    mimeTypes: ["video/mp4"],
    extensions: ["mp4"],
    safe: true,
    compatibleOutputs: [
      "webm",
      "avi",
      "mkv",
      "mov",
      "wmv",
      "flv",
      "gif",
      "mp3",
    ],
  },
  webm: {
    label: "WebM Video",
    category: "video",
    mimeTypes: ["video/webm"],
    extensions: ["webm"],
    safe: true,
    compatibleOutputs: ["mp4", "avi", "mkv", "mov", "wmv", "flv", "gif", "mp3"],
  },
  avi: {
    label: "AVI Video",
    category: "video",
    mimeTypes: ["video/x-msvideo"],
    extensions: ["avi"],
    safe: false,
    compatibleOutputs: [
      "mp4",
      "webm",
      "mkv",
      "mov",
      "wmv",
      "flv",
      "gif",
      "mp3",
    ],
  },
  mkv: {
    label: "MKV Video",
    category: "video",
    mimeTypes: ["video/x-matroska"],
    extensions: ["mkv"],
    safe: false,
    compatibleOutputs: [
      "mp4",
      "webm",
      "avi",
      "mov",
      "wmv",
      "flv",
      "gif",
      "mp3",
    ],
  },
  mov: {
    label: "QuickTime Video",
    category: "video",
    mimeTypes: ["video/quicktime"],
    extensions: ["mov"],
    safe: true, // Safari
    compatibleOutputs: [
      "mp4",
      "webm",
      "avi",
      "mkv",
      "wmv",
      "flv",
      "gif",
      "mp3",
    ],
  },
  wmv: {
    label: "WMV Video",
    category: "video",
    mimeTypes: ["video/x-ms-wmv"],
    extensions: ["wmv"],
    safe: false,
    compatibleOutputs: [
      "mp4",
      "webm",
      "avi",
      "mkv",
      "mov",
      "flv",
      "gif",
      "mp3",
    ],
  },
  flv: {
    label: "Flash Video",
    category: "video",
    mimeTypes: ["video/x-flv"],
    extensions: ["flv"],
    safe: false,
    compatibleOutputs: [
      "mp4",
      "webm",
      "avi",
      "mkv",
      "mov",
      "wmv",
      "gif",
      "mp3",
    ],
  },

  // Spreadsheets
  xlsx: {
    label: "Excel Spreadsheet",
    category: "spreadsheet",
    mimeTypes: [
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    ],
    extensions: ["xlsx"],
    safe: false,
    compatibleOutputs: ["csv", "json", "html", "pdf"],
  },
  xls: {
    label: "Legacy Excel",
    category: "spreadsheet",
    mimeTypes: ["application/vnd.ms-excel"],
    extensions: ["xls"],
    safe: false,
    compatibleOutputs: ["xlsx", "csv", "json", "pdf"],
  },
  csv: {
    label: "CSV",
    category: "spreadsheet",
    mimeTypes: ["text/csv", "application/csv"],
    extensions: ["csv"],
    safe: true,
    compatibleOutputs: ["xlsx", "json", "html", "pdf"],
  },

  // Data
  json: {
    label: "JSON",
    category: "data",
    mimeTypes: ["application/json"],
    extensions: ["json"],
    safe: true,
    compatibleOutputs: ["yaml", "xml", "csv", "xlsx", "toml"],
  },
  yaml: {
    label: "YAML",
    category: "data",
    mimeTypes: ["application/x-yaml", "text/yaml"],
    extensions: ["yaml", "yml"],
    safe: true,
    compatibleOutputs: ["json", "xml", "toml"],
  },
  yml: {
    label: "YAML",
    category: "data",
    mimeTypes: ["application/x-yaml", "text/yaml"],
    extensions: ["yaml", "yml"],
    safe: true,
    compatibleOutputs: ["json", "xml", "toml"],
  },
  xml: {
    label: "XML",
    category: "data",
    mimeTypes: ["application/xml", "text/xml"],
    extensions: ["xml"],
    safe: true,
    compatibleOutputs: ["json", "yaml", "toml"],
  },
  toml: {
    label: "TOML",
    category: "data",
    mimeTypes: ["application/toml"],
    extensions: ["toml"],
    safe: true,
    compatibleOutputs: ["json", "yaml", "xml"],
  },

  // Archives
  zip: {
    label: "ZIP Archive",
    category: "archive",
    mimeTypes: ["application/zip", "application/x-zip-compressed"],
    extensions: ["zip"],
    safe: false,
    compatibleOutputs: ["extract"], // 'extract' is a virtual format
  },
  rar: {
    label: "RAR Archive",
    category: "archive",
    mimeTypes: ["application/x-rar-compressed"],
    extensions: ["rar"],
    safe: false,
    compatibleOutputs: ["extract", "zip"],
  },
  "7z": {
    label: "7-Zip Archive",
    category: "archive",
    mimeTypes: ["application/x-7z-compressed"],
    extensions: ["7z"],
    safe: false,
    compatibleOutputs: ["extract", "zip"],
  },
  tar: {
    label: "TAR Archive",
    category: "archive",
    mimeTypes: ["application/x-tar"],
    extensions: ["tar"],
    safe: false,
    compatibleOutputs: ["extract", "zip", "gz"],
  },
  gz: {
    label: "GZIP Archive",
    category: "archive",
    mimeTypes: ["application/gzip"],
    extensions: ["gz"],
    safe: false,
    compatibleOutputs: ["extract", "zip", "tar"],
  },
};
